services:
  database:
    image: postgres:latest
    container_name: postgresql_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: WasteFreeHome
    networks:
      - server_network
    ports:
      - "5432:5432"
    volumes:
      - DBdata:/var/lib/postgresql/data
    tty: true
    
  server:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    container_name: fastapi_server
    networks:
      - server_network
    ports:
      - "9000:8000"
    volumes:
      - ./Server/app:/app
      - ./Server/requirements.txt:/app/requirements.txt
    depends_on:
      - database
    command: bash -c "pip install --no-cache-dir -r requirements.txt && \
                      cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mqtt_broker
    networks:
      - home_network
    ports:
      - "1883:1883"
    volumes:
      - ./MqttBroker/config:/mosquitto/config
      - ./MqttBroker/data:/mosquitto/data
      - ./MqttBroker/log:/mosquitto/log

  hub:
    image: tiangolo/uvicorn-gunicorn-fastapi:python3.10
    container_name: fastapi_hub
    networks:
      - home_network
    ports:
      - "8000:8000"
    volumes:
      - ./Hub/app:/app
      - ./Hub/requirements.txt:/app/requirements.txt
    depends_on:
      - mosquitto
      - server
    command: bash -c "pip install --no-cache-dir -r requirements.txt && \
                      cd .. && uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  DBdata:

networks:
  home_network:
  server_network:
