#
FROM python:3.11

#
WORKDIR /Server

#
COPY ./requirements.txt /Server/requirements.txt

#
RUN pip install --no-cache-dir --upgrade -r /Server/requirements.txt

#
COPY ./app /Server/app

#
COPY ./.env /Server/.env

#
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]